package com.ws101.castante.EcommerceApi.model;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * Represents a customer order in the ecommerce system.
 * 
 * This entity is persisted to the 'orders' table in the database.
 * Each order can contain multiple items through a One-to-Many relationship with OrderItem.
 * Orders track purchase history and order status.
 * 
 * @author Gabriel Castante
 * @version 1.0
 */
@Entity
@Table(name = "orders")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = "items")
@EqualsAndHashCode(exclude = "items")
public class Order {

    /**
     * Unique identifier for the order. Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique order identifier (e.g., "ORD-20260509-001"). 
     * Provides a human-readable reference for the order.
     */
    @Column(unique = true, nullable = false, length = 50)
    @NotBlank(message = "Order ID is required")
    private String orderId;

    /**
     * Name of the customer who placed the order. Required field.
     */
    @NotBlank(message = "Customer name is required")
    @Column(nullable = false, length = 100)
    private String customerName;

    /**
     * Timestamp when the order was created. Set automatically when the order is persisted.
     */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(nullable = false, updatable = false)
    private LocalDateTime orderDate;

    /**
     * Total price of the order. Sum of all order items' subtotals.
     */
    @NotNull(message = "Total price is required")
    private Double totalPrice;

    /**
     * Current status of the order (e.g., "PENDING", "PROCESSING", "SHIPPED", "DELIVERED", "CANCELLED").
     * Defaults to "PENDING" when created.
     */
    @Column(nullable = false, length = 50)
    @NotBlank(message = "Order status is required")
    private String status;

    /**
     * One-to-Many relationship to the OrderItem entity.
     * Each order can contain many items. Items are loaded lazily for performance.
     * When an order is deleted, all associated order items are also deleted (CascadeType.ALL).
     */
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    private Set<OrderItem> items = new HashSet<>();
}
