package com.ws101.castante.EcommerceApi.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Represents a single line item in a customer order.
 * 
 * This entity is persisted to the 'order_items' table in the database.
 * Each order item represents a specific product instance within an order.
 * An order item maintains the price and quantity at the time the order was placed.
 * 
 * @author Gabriel Castante
 * @version 1.0
 */
@Entity
@Table(name = "order_items")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = {"order", "product"})
@EqualsAndHashCode(exclude = {"order", "product"})
public class OrderItem {

    /**
     * Unique identifier for the order item. Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Many-to-One relationship to the Order entity.
     * Each order item belongs to exactly one order.
     * The foreign key is stored in the 'order_id' column.
     */
    @ManyToOne(optional = false)
    @JoinColumn(name = "order_id", nullable = false)
    private Order order;

    /**
     * Many-to-One relationship to the Product entity.
     * Each order item references exactly one product.
     * The foreign key is stored in the 'product_id' column.
     */
    @ManyToOne(optional = false)
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    /**
     * Quantity of the product in this order item. Required and must be positive.
     */
    @NotNull(message = "Quantity is required")
    @Min(value = 1, message = "Quantity must be at least 1")
    @Column(nullable = false)
    private Integer quantity;

    /**
     * Unit price of the product at the time the order was placed.
     * This is stored separately to maintain historical pricing even if the product price changes.
     */
    @NotNull(message = "Unit price is required")
    @Column(nullable = false)
    private Double unitPrice;

    /**
     * Subtotal for this order item (quantity * unitPrice).
     * Calculated field that should be updated whenever quantity or unitPrice changes.
     */
    @NotNull(message = "Subtotal is required")
    @Column(nullable = false)
    private Double subtotal;

    /**
     * Calculates and updates the subtotal based on quantity and unit price.
     * Should be called before persisting or updating the order item.
     */
    public void calculateSubtotal() {
        if (this.quantity != null && this.unitPrice != null) {
            this.subtotal = this.quantity * this.unitPrice;
        }
    }
}
