package com.ws101.castante.EcommerceApi.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Represents a single product in the ecommerce catalog.
 * 
 * This entity is persisted to the 'products' table in the database.
 * Each product belongs to exactly one category through a Many-to-One relationship.
 * 
 * @author Gabriel Castante
 * @version 2.0
 */
@Entity
@Table(name = "products")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = "category")
@EqualsAndHashCode(exclude = "category")
public class Product {

    /**
     * Unique identifier for the product. Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Product name. Required and must be between 3 and 100 characters.
     */
    @NotBlank(message = "Product name is required")
    @Size(min = 3, max = 100, message = "Product name must be at least 3 characters")
    private String name;

    /**
     * Detailed product description.
     */
    private String description;

    /**
     * Product price. Required and must be greater than 0.
     */
    @NotNull(message = "Price is required")
    @DecimalMin(value = "0.0", inclusive = false, message = "Price must be greater than 0")
    private Double price;

    /**
     * Many-to-One relationship to the Category entity.
     * Each product belongs to exactly one category.
     * The foreign key is stored in the 'category_id' column.
     */
    @ManyToOne(optional = false)
    @JoinColumn(name = "category_id", nullable = false)
    private Category category;

    /**
     * Available quantity in stock. Required and must be non-negative.
     */
    @NotNull(message = "Stock quantity is required")
    @Min(value = 0, message = "Stock quantity must be non-negative")
    private Integer stockQuantity;

    /**
     * URL to the product image.
     */
    private String imageUrl;
}
