package com.ws101.castante.EcommerceApi.model;

import java.util.Collection;
import java.util.HashSet;
import java.util.Set;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import jakarta.persistence.CollectionTable;
import jakarta.persistence.Column;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * User entity implementing Spring Security's UserDetails interface.
 * 
 * Represents a user in the ecommerce system with authentication and authorization information.
 * Users can have one or more roles (ADMIN, USER, SELLER) and are stored in the 'users' table.
 * 
 * @author Gabriel Castante
 * @version 1.0
 */
@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User implements UserDetails {

    /**
     * Unique identifier for the user. Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Username for login. Must be unique and between 3 and 50 characters.
     */
    @NotBlank(message = "Username is required")
    @Size(min = 3, max = 50, message = "Username must be between 3 and 50 characters")
    @Column(unique = true, nullable = false)
    private String username;

    /**
     * Email address. Must be unique and a valid email format.
     */
    @NotBlank(message = "Email is required")
    @Email(message = "Email must be valid")
    @Column(unique = true, nullable = false)
    private String email;

    /**
     * Hashed password. Stored using BCrypt.
     */
    @NotBlank(message = "Password is required")
    @Column(nullable = false)
    private String password;

    /**
     * Set of roles assigned to this user.
     * Roles are stored in a separate table 'user_roles' linked by user_id.
     * Fetched eagerly to avoid lazy loading issues in security context.
     */
    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "user_roles", joinColumns = @JoinColumn(name = "user_id"))
    @Column(name = "role")
    @Enumerated(EnumType.STRING)
    @Builder.Default
    private Set<Role> roles = new HashSet<>();

    /**
     * Indicates whether the user account is enabled or disabled.
     * Disabled accounts cannot log in.
     */
    @Builder.Default
    private boolean enabled = true;

    /**
     * Indicates whether the user account is locked.
     * Locked accounts cannot log in even if enabled.
     */
    @Builder.Default
    private boolean accountNonLocked = true;

    /**
     * Indicates whether the user credentials (password) have not expired.
     */
    @Builder.Default
    private boolean credentialsNonExpired = true;

    /**
     * Indicates whether the user account has not expired.
     */
    @Builder.Default
    private boolean accountNonExpired = true;

    /**
     * Converts user roles to Spring Security GrantedAuthority objects.
     * 
     * @return collection of authorities based on user roles
     */
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        Set<GrantedAuthority> authorities = new HashSet<>();
        for (Role role : roles) {
            authorities.add(new SimpleGrantedAuthority("ROLE_" + role.name()));
        }
        return authorities;
    }

    /**
     * Returns the username used for authentication.
     * 
     * @return the username
     */
    @Override
    public String getUsername() {
        return this.username;
    }

    /**
     * Returns the password used for authentication.
     * 
     * @return the hashed password
     */
    @Override
    public String getPassword() {
        return this.password;
    }

    /**
     * Indicates if the user account is non-expired.
     * 
     * @return true if the account is valid, false if expired
     */
    @Override
    public boolean isAccountNonExpired() {
        return this.accountNonExpired;
    }

    /**
     * Indicates if the user is not locked.
     * 
     * @return true if not locked, false if locked
     */
    @Override
    public boolean isAccountNonLocked() {
        return this.accountNonLocked;
    }

    /**
     * Indicates if the user credentials (password) have not expired.
     * 
     * @return true if credentials are valid, false if expired
     */
    @Override
    public boolean isCredentialsNonExpired() {
        return this.credentialsNonExpired;
    }

    /**
     * Indicates if the user account is enabled.
     * 
     * @return true if enabled, false if disabled
     */
    @Override
    public boolean isEnabled() {
        return this.enabled;
    }
}
